version: '3.9'

services:
  db:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
      - ./db/create_database.sql:/docker-entrypoint-initdb.d/spacetrack.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=starlink
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  data_loader:
    container_name: data_loader
    build: .
    command: python load_data.py
    volumes:
      - .:/code
    depends_on:
      db:
        condition: service_healthy

  api:
    container_name: app
    build: .
    command: python api.py
    volumes:
      - .:/code
    ports:
      - "8080:5000"
    depends_on:
      db:
        condition: service_healthy
      data_loader:
        condition: service_completed_successfully
